import { Metadata } from 'next'
import { PrimeReactProvider } from 'primereact/api'

import 'primeicons/primeicons.css'
import 'primereact/resources/primereact.min.css'
import 'primereact/resources/themes/lara-light-blue/theme.css'
import '@/styles/index.sass'


export const metadata: Metadata = {
  // General
  metadataBase: new URL('https://linkchar.com'), // Replace with an env variable with proyect domain
  applicationName: 'Boda de Lucas y Flor',
  generator: 'Next.js',
  title: {
    default: 'Boda de Lucas y Flor',
    template: '%s | Linkchar',
  },
  description: 'Boda de Lucas y Flor - Created by Lucas Ojeda De Sousa (Lukway)',
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
  },
  referrer: 'origin-when-cross-origin',
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: 'white' },
    { media: '(prefers-color-scheme: dark)', color: 'black' },
  ],
  category: 'Software Development',
  // Author
  // Add all team members
  authors: [{ name: 'Lucas Ojeda De Sousa (Lukway)', url: 'lukway.dev@gmail.com' }],
  creator: 'Lucas Ojeda De Sousa (Lukway)',
  publisher: 'Linkchar - Next Template',
  // URL
  manifest: '/manifest.json',
  alternates: {
    canonical: '/',
    languages: {
      'en-US': '/',
    },
  },
  // SEO
  keywords: ['Boda de Lucas y Flor'],
  openGraph: {
    title: 'Boda de Lucas y Flor',
    description: 'Generated by Lucas Ojeda De Sousa',
    url: 'http://localhost:3000',
    type: 'book',
    siteName: 'Boda de Lucas y Flor',
    images: [
      {
        url: '/seo-image.png',
        width: 800,
        height: 465,
      },
      {
        url: '/seo-image.png',
        width: 1400,
        height: 810,
        alt: 'My custom alt',
      },
    ],
    locale: 'en_US',
    authors: ['Lucas Ojeda De Sousa (Lukway)'],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Boda de Lucas y Flor',
    description: 'Boda de Lucas y Flor',
    siteId: '123456789',
    creator: '@linkchar',
    creatorId: '123456789',
    images: {
      url: '/seo-image.png',
      alt: 'Boda de Lucas y Flor',
    }
  },
  // Robots
  robots: {
    index: true,
    follow: true,
    nocache: true,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  // Icons
  icons: {
    icon: [
      { url: '/16.png', sizes: '16x16', type: 'image/png' },
      { url: '/32.png', sizes: '32x32', type: 'image/png' },
      { url: '/36.png', sizes: '36x36', type: 'image/png' },
      { url: '/48.png', sizes: '48x48', type: 'image/png' },
      { url: '/57.png', sizes: '57x57', type: 'image/png' },
      { url: '/60.png', sizes: '60x60', type: 'image/png' },
      { url: '/72.png', sizes: '72x72', type: 'image/png' },
      { url: '/76.png', sizes: '76x76', type: 'image/png' },
      { url: '/96.png', sizes: '96x96', type: 'image/png' },
      { url: '/114.png', sizes: '114x114', type: 'image/png' },
      { url: '/120.png', sizes: '120x120', type: 'image/png' },
      { url: '/144.png', sizes: '144x144', type: 'image/png' },
      { url: '/150.png', sizes: '150x150', type: 'image/png' },
      { url: '/152.png', sizes: '152x152', type: 'image/png' },
      { url: '/180.png', sizes: '180x180', type: 'image/png' },
      { url: '/192.png', sizes: '192x192', type: 'image/png' },
      { url: '/256.png', sizes: '256x256', type: 'image/png' },
      { url: '/310.png', sizes: '310x310', type: 'image/png' },
      { url: '/348.png', sizes: '348x348', type: 'image/png' },
      { url: '/512.png', sizes: '512x512', type: 'image/png' },
    ],
    shortcut: {
      url: '/144.png',
      sizes: '144x144',
      type: 'image/png'
    },
    apple: [
      { url: '/57.png', sizes: '57x57', type: 'image/png' },
      { url: '/60.png', sizes: '60x60', type: 'image/png' },
      { url: '/72.png', sizes: '72x72', type: 'image/png' },
      { url: '/76.png', sizes: '76x76', type: 'image/png' },
      { url: '/114.png', sizes: '114x114', type: 'image/png' },
      { url: '/120.png', sizes: '120x120', type: 'image/png' },
      { url: '/144.png', sizes: '144x144', type: 'image/png' },
      { url: '/152.png', sizes: '152x152', type: 'image/png' },
      { url: '/180.png', sizes: '180x180', type: 'image/png' },
    ],
    other: {
      rel: 'apple-touch-icon-precomposed',
      url: '/144.png',
      sizes: '144x144',
      type: 'image/png'
    },
  },
  // Apple
  appleWebApp: {
    title: 'Boda de Lucas y Flor',
    statusBarStyle: 'black-translucent',
    startupImage: [
      '/splash.png'
    ],
  },
  // Extras
  bookmarks: ['https://linkchar.com']
}

interface Props {
  children: React.ReactNode
}
export default function Layout({ children }: Props) {
  return (
    <html lang="en">
      <body>
        <PrimeReactProvider>
          { children }
        </PrimeReactProvider>
      </body>
    </html>
  )
}
